# Generated by Django 4.0.1 on 2022-02-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basquetbolistas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('contenido', models.CharField(max_length=40000)),
            ],
        ),
        migrations.CreateModel(
            name='Futbolistas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('contenido', models.CharField(max_length=40000)),
            ],
        ),
        migrations.CreateModel(
            name='Rugbiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('contenido', models.CharField(max_length=40000)),
            ],
        ),
    ]
